// RUN: zero-count-opt %s | FileCheck %s
//
// Roundtrip test: verify the op parses and prints back correctly.
// No passes are applied — this purely exercises the parser and printer
// generated by ODS from ZeroCountOps.td.

// CHECK-LABEL: func.func @test_count_zeros
func.func @test_count_zeros(%x: i32) -> i32 {
  // CHECK: zero_count.count_zeros %arg0 : i32
  %result = zero_count.count_zeros %x : i32
  func.return %result : i32
}
