#include "seki_hw/SekiHwAttrs.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"

// Enums are generated by tblgen backend once and doesn't have any #ifdef, content is just plain C++ func impl
#include "seki_hw/SekiHwEnums.cpp.inc"

// Custom attr methods and verifiers go here (generated class definitions live in SekiHwDialect.cpp)
